name: APK Build

on:
  push:
    branches: [ main, develop, sc ]

jobs:
  gplay:
    name: Build unsigned GPlay APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Assemble FDroid unsigned apk
        run: ./gradlew clean assembleFdroidRelease --stacktrace
        
      - name: Assemble GPlay unsigned apk
        run: ./gradlew clean assembleGplayRelease --stacktrace
      
      - name: Sign artifact
        id: signArtifact
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: vector/build/outputs/apk/gplay/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          
      - name: Sign artifact2
        id: signArtifact2
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: vector/build/outputs/apk/fdroid/release
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
    
      - name: Upload Gplay signed APKs
        uses: actions/upload-artifact@v2
        with:
          name: release-apk-signed-GPlay
          path: |
            vector/build/outputs/apk/gplay/release/*.apk
            
      - name: Upload Fdroid signed APKs
        uses: actions/upload-artifact@v2
        with:
          name: release-apk-signed-Fdroid
          path: |
            vector/build/outputs/apk/fdroid/release/*.apk
